env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules:
  '@typescript-eslint/indent': ['error', 4]
settings:
  react:
    version: "detect" # Automatically detect the react version

